force-app/main/default/objects/Contact_Mapping__mdt/Contact_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Contact Mapping</label>
    <pluralLabel>Contact Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Mapping__mdt/fields/Outbound_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Mapping__c</fullName>
    <label>Outbound Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Mapping__mdt/fields/Rightsline_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Rightsline_Template_Id__c</fullName>
    <label>Rightsline Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Mapping__mdt/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <label>Salesforce Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Mapping__mdt/fields/Salesforce_Object_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object_Record_Type__c</fullName>
    <label>Salesforce Object Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Log__c/Package_Log__c.object-meta.xml
<CustomObject>
    <label>Package Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Package Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Log__c/fields/Dump__c.field-meta.xml
<CustomField>
    <fullName>Dump__c</fullName>
    <label>Dump</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package_Log__c/fields/isRetryLog__c.field-meta.xml
<CustomField>
    <fullName>isRetryLog__c</fullName>
    <label>isRetryLog</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/batchInitialContactSync.cls
public with sharing class batchInitialContactSync {
}
/*global with sharing class batchInitialContactSync implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        checkAccess();

        List<Contact_Mapping__mdt> contactMappingList = [SELECT Id, Outbound_Mapping__c, Rightsline_Template_Id__c, Salesforce_Object__c, Salesforce_Object_Record_Type__c FROM Contact_Mapping__mdt WHERE Salesforce_Object__c != null];

        //List<List<SObject>> syncRecordLists = new List<List<SObject>>();
        List<sObject> sfRecordObjectList = new List<sObject>();
        sfRecordObjectList.addAll(contactMappingList);
        //syncRecordLists.add(contactMappingList);

        for (Contact_Mapping__mdt contactMap : contactMappingList) {
            List<String> sfFieldList = new List<String>();
            List<Object> fieldObjectList = (List<Object>)JSON.deserializeUntyped(contactMap.Outbound_Mapping__c);
            String queryString = 'SELECT Id';

            for (Object fieldObject : fieldObjectList) {
                Map<String,Object> fieldMap = (Map<String,Object>)fieldObject;

                if (String.isNotEmpty((String)fieldMap.get('sfField'))) {
                    if (!sfFieldList.contains((String)fieldMap.get('sfField'))) {
                        sfFieldList.add((String)fieldMap.get('sfField'));
                        queryString += ', ' + (String)fieldMap.get('sfField');
                    }
                    System.debug(queryString);
                }
            }

            queryString += ' FROM ' + contactMap.Salesforce_Object__c;
            System.debug(queryString);
            System.debug(Database.query(queryString));

            sfRecordObjectList.addAll(Database.query(queryString));
            //syncRecordLists.add(sfRecordObjectList);
        }

        //return syncRecordLists;
        return sfRecordObjectList;
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        delete scope;
    }

    global void finish(Database.BatchableContext BC) {
        AggregateResult ar = [SELECT count(Id) packageLogCount FROM Package_Log__c];
        if((Integer)ar.get('packageLogCount') > 0) {
            Database.executeBatch(new batchDeletePackageLogs(), 2000);
        }
    }

    private static Map<String, Map<String, Set<String>>> accessChecks = new Map<String, Map<String, Set<String>>> {
        'Package_Log__c' => new Map<String, Set<String>> {
            'Create' => new Set<String> {
                'Id, Dump__c, isRetryLog__c, Location__c, Message__c, Object_Api_Name__c, Operation__c, Record_Id__c, Type__c'
            },
            'Read' => new Set<String> {
                'Id, Dump__c, isRetryLog__c, Location__c, Message__c, Object_Api_Name__c, Operation__c, Record_Id__c, Type__c'
            }
        }
    };

    private static void checkAccess(){
        DmlManager.checkAccess(accessChecks);
    }
}*/